ALTER TABLE bot ADD fieldsInput VARCHAR(120) NOT NULL;
ALTER TABLE bot ADD fieldsOutput VARCHAR(120) NOT NULL;
ALTER TABLE bot ADD typeFileIn VARCHAR(4) NOT NULL;
ALTER TABLE bot ADD separatorFile VARCHAR(1) NULL;