server:
  name: icaptor-server
  host: localhost
  port: 8082

broker:
  user: guest
  pass: guest
  host: 34.231.45.229
  port: 30001
  queue.send.schedularTime: 5000 #milli second


io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file

---
server:
  name: icaptor-server
  host: localhost
  port: 8082

spring:
  profiles: dev

broker:
  user: guest
  pass: guest
  host: localhost
  queue.send.schedularTime: 5000 #milli second


io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file

# temporario
retries: 5
