server:
  name: icaptor-server
  host: localhost
  port: 8082
io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file

icaptor:
  data-source:
    host: http://localhost:8085
  broker:
    user: guest
    pass: guest
    host: 34.231.45.229
    port: 15762
    queue-send-schedular-time: 5000 #milli second
  elasticSearch: http://54.232.36.27:9200

---
server:
  name: icaptor-server
  host: localhost
  port: 8082

spring:
  profiles: dev

io:
  worker.dir: ${user.home}/.icaptor-agent
  worker.file: ${user.home}/.icaptor-out-file
  file-read: ${user.home}/.icaptor-read-file


icaptor:
  data-source:
    host: http://localhost:8085
  broker:
    user: guest
    pass: guest
    host: localhost
    port: 15672
    queue-send-schedular-time: 5000 #milli second
  elasticSearch: http://54.232.36.27:9200



