server:
  name: icaptor-server
  host: localhost
  port: 8082

broker:
  user: guest
  pass: guest
  host: 54.224.242.0

io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file

