#spring:
#  datasource:
#    url: jdbc:mysql://34.206.50.158:3306/icaptor
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: ic@ptor123
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate.ddl-auto: update

#profiles: dev
#server:
#  name: icaptor-server
#  host: localhost
#  port: 8082
#  contextPath: /icaptor


#spring:
#  thymeleaf.mode: HTML5
#  datasource:
#    url: jdbc:mysql://localhost:3306/icaptor?autoReconnect=true&useSSL=false
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver
#  hikari:
#    connection-timeout: 60000
#    maximum-pool-size: 5
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      show-sql: true
#
#  jackson.serialization.fail-on-empty-beans: false
#
#  data.rest.detection-strategy: annotated
#
#flyway:
#    enabled: "true"
#    validateOnMigrate: true
