version: '2'

services:

  icaptor-cloud:
    build: icaptor-cloud/.
    container_name: icaptor-cloud
    ports:
      - "8082:8082"
    environment:
      - spring.profiles.active=dev
      - icaptor.data-source.host=http://54.232.16.190:8085
      - icaptor.broker.host=54.232.16.190

  icaptor-api:
    build: icaptor-web-security/.
    container_name: icaptor-api
    ports:
      - "8014:8014"
      - "5005:5005"
    environment:
      - icaptor.data-source.host=http://54.232.16.190:8085
      - icaptor.server.host=54.232.16.190:8082
      - icaptor.origin-permitida=http://54.232.16.190:4200

  icaptor-monitoring:
    build: icaptor-monitoring/.
    container_name: icaptor-monitoring
    ports:
      - "8090:8090"
    environment:
      - icaptor.data-source.host=http://54.232.16.190:8085
      - icaptor.broker.host=54.232.16.190
      - icaptor.elasticSearch=http://54.232.16.190:9200





