version: '3'

services:

  icaptor-broker:
    image: rabbitmq:3-management
    networks:
      - interna
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1
      placement:
            constraints: [node.role == manager]
#    volumes:
#     - $PWD/storage/rabbitmq:/var/lib/rabbitmq
    environment:
#     - RABBITMQ_ERLANG_COOKIE=icaptor-automation
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
#     - CLUSTERED=true

  icaptor-alpine-redis:
    image: smebberson/alpine-redis
    networks:
      - interna
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
#    environment:
#      - MYSQL_DATABASE=icaptor
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root

  icaptor-mysql:
    image: mysql/mysql-server
    networks:
      - interna
    ports:
      - "3306:3306"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MYSQL_DATABASE=icaptor
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  icaptor-redis:
    image: fiveware/icaptor-redis
    networks:
      - interna
    ports:
      - "8086:8086"
      - "8009:8009"
    depends_on:
      - icaptor-alpine-redis
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - spring.profiles.active=local
      - spring.redis.hostname=icaptor-alpine-redis
      - spring.redis.port=6379

  icaptor-data:
    image: fiveware/icaptor-persistence
    networks:
      - interna
    ports:
      - "8085:8085"
      - "8005:8005"
    depends_on:
      - icaptor-mysql
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - spring.profiles.active=dev
      - spring.datasource.url=jdbc:mysql://icaptor-mysql:3306/icaptor?createDatabaseIfNotExist=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driverClassname=com.mysql.jdbc.Driver

  icaptor-cloud:
    image: fiveware/icaptor-cloud
    networks:
      - interna
    ports:
      - "8082:8082"
      - "8003:8003"
    depends_on:
      - icaptor-broker
      - icaptor-data
    environment:
      - spring.profiles.active=dev
      - icaptor.data-source.host=http://icaptor-data:8085
      - icaptor.broker.host=icaptor-broker
      - icaptor.broker.port=15672

  icaptor-api:
    image: fiveware/icaptor-web-security
    networks:
      - interna
    ports:
      - "8014:8014"
      - "8006:8006"
    environment:
      - icaptor.data-source.host=http://icaptor-data:8085
      - icaptor.server.host=http://icaptor-cloud:8082
      - icaptor.origin-permitida=http://localhost:4200
      - icaptor.redis=http://icaptor-redis:8086

  icaptor-monitoring:
    image: fiveware/icaptor-monitoring
    networks:
      - interna
    ports:
      - "8090:8090"
      - "8004:8004"
    environment:
      - icaptor.data-source.host=http://icaptor-data:8085
      - icaptor.broker.host=icaptor-broker
      - icaptor.elasticSearch=http://54.232.36.27:9200

  icaptor-workflow:
    image: fiveware/icaptor-workflow
    networks:
      - interna
    ports:
      - "8020:8020"
      - "8007:8007"
    environment:
      - icaptor.data-source.host=http://icaptor-data:8085
      - icaptor.broker.host=icaptor-broker

networks:
  interna:



