version: '2'

services:

#  icaptor-api:
#    build: icaptor-web-security/.
#    ports:
#      - "8014:8014"
#    environment:
#      - icaptor.data-source=http://192.168.0.27:8085
#      - icaptor.server.host=192.168.0.27:8082
#
#  icaptor-agent:
#    build: icaptor-agent/.
#    environment:
#      - icaptor.data-source=http://192.168.0.27:8085
#      - icaptor.server.host=192.168.0.27:8082
#
#  icaptor-cloud:
#    build: icaptor-cloud/.
#    ports:
#      - "8082:8082"
#    environment:
#      - icaptor.data-source=http://192.168.0.27:8085
#      - icaptor.broker.host=192.168.0.27

  icaptor-data:
    build: icaptor-persistence/.
    ports:
      - "8085:8085"
    environment:
      - spring.profiles.active=dev
      - db.host=192.168.0.27
#    links:
#      - mysqldbserver

#  icaptor-ui:
#    image: icaptor-ui
#    ports:
#      - "4200:4200"
#    links:
#      - icaptor-api
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=icaptor

