server:
  name: icaptor-web-server
  host: 192.168.0.14
  port: 8014


icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200
  data-source:
    host: http://192.168.0.14:8085
  server:
    host: http://192.168.0.14:8082

