server:
  name: icaptor-web-server
  host: localhost
  port: 8014


icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200
  data-source:
    host: http://localhost:8085
  server:
    host: http://localhost:8082
  elasticSearch: http://54.232.36.27:9200
  redis: http://54.232.36.27:8086
