server:
  name: icaptor-web-server
  host: localhost
  port: 8014
icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200

---
server:
  name: icaptor-web-server
  host: localhost
  port: 8014
icaptor:
  seguranca:
    enable-https: true
  origin-permitida: http://localhost:4200
spring:
  profiles:
    active: prod

