server:
  name: icaptor-web-server
  host: localhost
  port: 8014


icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200
  data-source:
    host: http://localhost:8015

