version: '2'

services:

  icaptor-data:
    build: .
    container_name: icaptor-data
    ports:
      - "8085:8085"
    environment:
      - spring.profiles.active=dev
      - spring.datasource.url=jdbc:mysql://34.235.186.255:3306/icaptor?createDatabaseIfNotExist=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driverClassname=com.mysql.jdbc.Driver
