server:
  name: icaptor-monitoring
  host: localhost
  port: 8090

io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file


icaptor:
  data-source:
    host: http://localhost:8085
  broker:
    user: guest
    pass: guest
    host: 34.231.45.229
    port: 30001
    queue-send-schedular-time: 5000 #milli second
---
spring:
  profiles:
    active: dev
server:
  name: icaptor-monitoring
  host: localhost
  port: 8090

io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file

icaptor:
  data-source:
    host: http://localhost:8085
  broker:
    user: guest
    pass: guest
    host: 54.232.16.190
    port: 15672
    queue-send-schedular-time: 5000 #milli second
