spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
  profile: test

flyway:
    enabled: "false"
    validateOnMigrate: true