icaptor:
  server:
    name: icaptor-server
    host: localhost:8082
    ip: localhost
    data-source:
      host: http://localhost:8085
  elasticSearch: http://54.232.96.63:9200

  broker:
    user: guest
    pass: guest
#    host: 54.232.16.190
#    port: 15672
    host: localhost
    port: 15672
    queue-send-schedular-time: 5000 #milli second

io:
  extension.input.file: .csv
  bot.extension.file: .jar


