server.port: ${PORT:${SERVER_PORT:0}}

spring.http:
    multipart:
        max-file-size: 1024MB
        max-request-size: 1024MB

icaptor:
  server:
    name: icaptor-server
    host: http://localhost:8082
    ip: 127.0.0.1
  data-source:
    host: http://localhost:8085
  broker:
    user: guest
    pass: guest
    host: 34.231.45.229
    port: 30001
    queue-send-schedular-time: 5000 #milli second

io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file


---
server.port: ${PORT:${SERVER_PORT:0}}


spring.http:
    multipart:
        max-file-size: 1024MB
        max-request-size: 1024MB
spring:
  profiles: dev

icaptor:
  server:
    name: icaptor-server
    host: 192.168.0.14:8082
    ip: 192.168.0.14
    data-source:
      host: http://192.168.0.14:8085
  broker:
    user: guest
    pass: guest
    host: 192.168.0.14
    queue-send-schedular-time: 5000 #milli second

io:
  worker.dir: ${user.home}/.icaptor-agent
  worker.file: ${user.home}/.icaptor-out-file
  file-read: ${user.home}/.icaptor-read-file




