server.port: ${PORT:${SERVER_PORT:0}}

spring.http:
    multipart:
        max-file-size: 1024MB
        max-request-size: 1024MB

server-icaptor: icaptor-server
host: localhost:8082
agent: agentTeste-1
ip: 127.0.0.1

broker:
  user: guest
  pass: guest
  host: 54.224.242.0
  queue.send.schedularTime: 5000 #milli second

io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file
  
spring:
  thymeleaf.mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/icaptor?autoReconnect=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true

  jackson.serialization.fail-on-empty-beans: false

  data.rest.detection-strategy: annotated



flyway:
    enabled: "true"
    validateOnMigrate: true