server.port: ${PORT:${SERVER_PORT:0}}

spring.http:
    multipart:
        max-file-size: 1024MB
        max-request-size: 1024MB

icaptor:
  server:
    name: icaptor-server
    host: http://localhost:8082
    ip: 127.0.0.1
  data-source:
    host: http://localhost:8085
  broker:
    user: guest
    pass: guest
    host: 34.231.45.229
    port: 30001
    queue-send-schedular-time: 5000 #milli second

io:
  worker.dir: ${user.home}/.icaptor-agent
  worker.file: ${user.home}/.icaptor-out-file
  file-read: ${user.home}/.icaptor-read-file


---
server.port: ${PORT:${SERVER_PORT:0}}


spring.http:
    multipart:
        max-file-size: 1024MB
        max-request-size: 1024MB
spring:
  profiles: dev

icaptor:
  server:
    name: icaptor-server
    host: localhost:8082
    ip: localhost
    data-source:
      host: http://localhost:8085
  broker:
    user: guest
    pass: guest
    host: 54.232.16.190
    port: 15672
    queue-send-schedular-time: 5000 #milli second

io:
  worker.dir: ${user.home}/.icaptor-agent
  worker.file: ${user.home}/.icaptor-out-file
  file-read: ${user.home}/.icaptor-read-file




